project_id = "lojjhatxyaxxbxiqbuwp"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
major_version = 17

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[studio]
port = 54323


